export const SET_LOCATION = "SET_LOCATION";
export const SET_LOCATION_SUCCESS = "SET_LOCATION_SUCCESS";
export const SET_LOCATION_FAIL = "SET_LOCATION_FAIL";
export const SEARCH_LOCATION_SUCCESS = "SEARCH_LOCATION_SUCCESS";
export const SEARCH_LOCATION_FAIL = "SEARCH_LOCATION_FAIL";
export const CURRENT_WEATHER_REQUEST = "CURRENT_WEATHER_REQUEST";
export const CURRENT_WEATHER_REQUEST_SUCCESS =
  "CURRENT_WEATHER_REQUEST_SUCCESS";
export const CURRENT_WEATHER_REQUEST_FAIL = "CURRENT_WEATHER_REQUEST_FAIL";
export const FORECAST_REQUEST = "FORECAST_REQUEST";
export const FORECAST_REQUEST_SUCCESS = "FORECAST_REQUEST_SUCCESS";
export const FORECAST_REQUEST_FAIL = "FORECAST_REQUEST_FAIL";
